apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  selector:
    app: talentcloud
    tier: frontend
  ports:
  - name: "80"
    port: 80
    targetPort: 80
  - name: "443"
    port: 443
    targetPort: 443
  loadBalancerIP: 52.179.85.224
  type: LoadBalancer
status:
  loadBalancer: {}
