apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f ../docker-compose.yml
    kompose.version: 1.18.0 (06a2e56)
  creationTimestamp: null
  labels:
    io.kompose.service: talentcloud
  name: talentcloud
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: talentcloud
    spec:
      containers:
      - name: talentcloud
        image: june10k8sacr.azurecr.io/talentcloud
        ports:
        - containerPort: 9000
        resources: {}
        volumeMounts:
        - mountPath: /var/log
          name: logs
        - mountPath: /var/www/
          name: talentcloud
        workingDir: /var/www/
      restartPolicy: Always
      imagePullSecrets:
        - name: aks-login
      volumes:
      - name: logs
        persistentVolumeClaim:
          claimName: logs
      - name: talentcloud
        persistentVolumeClaim:
          claimName: talentcloud
status: {}
