apiVersion: v1
kind: Service
metadata:
  name: talentcloud
spec:
  selector:
    app: talentcloud
    tier: backend
  ports:
  - name: "9000"
    port: 9000
    targetPort: 9000
status:
  loadBalancer: {}
