apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: talentcloud
  name: talentcloud
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 16Gi
status: {}
