
pool:
  name: Hosted Ubuntu 1604

variables:
- group: tc-build-variables

steps:
- task: DockerCompose@0
  displayName: 'Build services'
  inputs:
    containerregistrytype: 'Azure Container Registry'
    azureSubscription: $(azureSubscription)
    azureContainerRegistry: '{"loginServer":"tcdockeracr.azurecr.io", "id" : "/subscriptions/$(azureSubscriptionId)/resourceGroups/tc-docker-rg/providers/Microsoft.ContainerRegistry/registries/tcdockeracr"}'
    dockerComposeFile: '**/docker-compose.yml'
    action: 'Build services'

- task: DockerCompose@0
  displayName: 'Run test-fullstack in Docker Compose'
  inputs:
    dockerComposeFile: '**/docker-compose.yml'
    containerregistrytype: 'Azure Container Registry'
    azureSubscription: $(azureSubscription)
    azureContainerRegistry: '{"loginServer":"tcdockeracr.azurecr.io", "id" : "/subscriptions/$(azureSubscriptionId)/resourceGroups/tc-docker-rg/providers/Microsoft.ContainerRegistry/registries/tcdockeracr"}'
    action: 'Run a Docker Compose command'
    dockerComposeCommand: 'run talentcloud-op /opt/TalentCloud/test-fullstack.sh master'

- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'JUnit'
    testResultsFiles: '**/*-junit.xml'
    searchFolder: /opt/TalentCloud/reports/

- task: DockerCompose@0
  displayName: 'Push services to registry'
  inputs:
    containerregistrytype: 'Azure Container Registry'
    azureSubscription: $(azureSubscription)
    azureContainerRegistry: '{"loginServer":"tcdockeracr.azurecr.io", "id" : "/subscriptions/$(azureSubscriptionId)/resourceGroups/tc-docker-rg/providers/Microsoft.ContainerRegistry/registries/tcdockeracr"}'
    dockerComposeFile: '**/docker-compose.yml'
    action: 'Push services'
