
pool:
  name: Hosted Ubuntu 1604

variables:
  CI: true
  CI_BRANCH: master

steps:
- task: DockerCompose@0
  displayName: 'Run test-fullstack in Docker Compose'
  inputs:
    dockerComposeFile: 'docker-compose.yml'
    dockerComposeCommand: 'run talentcloud-op /opt/TalentCloud/test-fullstack.sh master'

- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'JUnit'
    testResultsFiles: '**/*-junit.xml'
    searchFolder: /opt/TalentCloud/reports/

- task: DockerCompose@1
  inputs:
    containerregistrytype: 'Azure Container Registry'
    azureSubscription: 'Free Trial (0539e475-854e-4046-8ce5-5757e376c655)'
    azureContainerRegistry: '{"loginServer":"tcdockeracr.azurecr.io", "id" : "/subscriptions/0539e475-854e-4046-8ce5-5757e376c655/resourceGroups/tc-docker-rg/providers/Microsoft.ContainerRegistry/registries/tcdockeracr"}'
    dockerComposeFile: '**/docker-compose.yml'
    action: 'Push services'
