
pool:
  name: Hosted Ubuntu 1604

variables:
  CI: true
  CI_BRANCH: master

steps:
- task: DockerCompose@0
  displayName: 'Run test-fullstack in Docker Compose'
  inputs:
    dockerComposeFile: 'docker-compose.yml'
    dockerComposeCommand: 'run talentcloud-op /opt/TalentCloud/test-fullstack.sh master'

- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'JUnit'
    testResultsFiles: '**/*-junit.xml'
    searchFolder: /opt/TalentCloud/reports/