FROM nginx:1.13.9-alpine

COPY etc/nginx/default.conf /etc/nginx/conf.d/default.conf
COPY service/wait-for-setup.sh /usr/local/bin/

RUN echo "daemon off;" >> /etc/nginx/nginx.conf
CMD ["/usr/local/bin/wait-for-setup.sh", "nginx"]
