apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f ../docker-compose.yml
    kompose.version: 1.18.0 (06a2e56)
  creationTimestamp: null
  labels:
    io.kompose.service: nginx
  name: nginx
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: nginx
    spec:
      containers:
      - image: nginx
        name: nginx-setup
        ports:
        - containerPort: 80
        - containerPort: 443
        resources: {}
        volumeMounts:
        - mountPath: /var/www
          name: TalentCloud
        - mountPath: /opt/TalentCloud/ssl
          name: ssl
        - mountPath: /var/log
          name: logs
        workingDir: /var/www/
      restartPolicy: Always
      volumes:
      - name: TalentCloud
        persistentVolumeClaim:
          claimName: TalentCloud
      - name: ssl
        persistentVolumeClaim:
          claimName: ssl
      - name: logs
        persistentVolumeClaim:
          claimName: logs
status: {}
